apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Real-IP: $remote_addr";
  name: counter-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: counter-app.duckdns.org
      http:
        paths:
          - path: /counter(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 8080
